### ISSUE TITLE
Milestone Goal UX improvements

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/developers#42]
# Milestone Goal Issues

It's often useful to ask "what are the top-level / final / goal issues that must be resolved to complete this milestone?"

A milestone is a sub-DAG of issues which may depend on each other (without cycles), and they may depend on issues outside of the milestone, and they may be dependencies of issues outside of the milestone.

The "top-level / final / goal issues" are those issues in a milestone which have no dependents which are also in that milestone. Let's call these "milestone goals" henceforth.

The milestone goals are often useful to focus on or refer to, because they tend to:

- be higher-level than the other dependencies,
- map closer to (or even define) the overall goal of the milestone, and
- be a shorter list that's easier to communicate about.

For example, let's say a milestone is for a full node release, and the goal is "fix two known bugs, introduce a new feature, and release a package". Then the milestone goals might consist of four issues for exactly those four goals. Meanwhile, it may include a lot of dependencies. An example might be "refactor the Foo subsystem" which is a dependency of one of the bugfixes and the feature. We typically don't want to include that refactor task when we're describing the release goals broadly, such as to users, because many users would not care about internal code properties. Also, for developers, it's useful to remain focused on the top-level "why?" goals during a milestone.

## Tracking Milestone Goals w/ DAG View & GitHub

With the current `zcash-issue-dag.py` boxes are drawn for GitHub Milestones.

One can visually scan to see milestone goals by finding all nodes within a milestone box that have no dependents within the same milestone. Visually, this can be done by following dependency links within the box towards the right until the only rightward links cross the box boundary.

On the other hand, sometimes it's helpful to have a list of the milestone goals. If you view the milestone page in GitHub, it lists _all_ issues, including both goals and dependencies. GitHub doesn't have issue dependencies, so there's no way to filter or search for just those goals without some kind of work-around.

### Milestone Goal Label Work-Around

In this work-around the milestone goals have a `Milestone Goal` label added manually to match the DAG state. This makes it possible to search for them.

Downsides: managing the labels consistently to match the DAG and Milestone.

### Capstone Issue Work-Around

One work-around is to introduce a "capstone issue". These are issues that map one-to-one to GitHub milestones and their direct dependents are the milestone goals. When this work-around is used, the visual scanning above changes to scanning for the direct dependents of the capstone issue.

When using a capstone issue, the list of goals are visible via Zenhub (or Zenhub extension on Github) as the direct dependencies of the capstone, so there's a convenient list.

The main drawback for capstone issues a one-to-one mapping must be maintained to the Milestone. For example, if a new goal issue is introduced to the Milestone, it must also be added as a direct dependency of the capstone and vice-versa.

Note: here we're describing capstones as purely for tracking, distinct from any "natural capstone" a milestone may have. For example a `zcashd` release milestone may have a capstone like "announce release", with dependencies like "publish binary packages", "update github releases page", …

# Improvements Brainstorm

Do we need to improve this? If so, how?

Here are some brainstormed approaches. Feel free to add more in comments.

## Automate Goal Issue Identification

The `zcash-issue-dag.py` tool could automate goal issue tracking in various ways (some combination of these):

- spit out the goals for each milestone on the commandline, perhaps in `md` format with links.
- color the graphviz nodes distinctly for rapid visual identification.
- automatically add/remove a github label, like `milestone goal`. This would make github-without-zenhub searches possible.
  - The milestone page could even link to the appropriate search so that it's easy for any user (even non-DAG-aware) to quickly find the goals for a milestone.

This approach could help remove the need for capstone issues altogether.

Advantages:

- Anyone who uses/browses GitHub milestones (without awareness of dag tool) will see what they expect.
- No need to manage capstones and synchronize state; maintains a single source of truth.

Disadvantages:

- This would introduce GitHub metadata _writes_ into the dag tool (if it is adding/removing labels). This has a few implications:
  - It requires more capabilities so presents a greater security risk.
  - The GitHub state will be out-of-sync until someone runs the tool.
  - If every dev triggers these updates, there'd be needless excessive writes; if devs have slightly different versions/behavior the GitHub label state might "thrash" as different devs update.
  - We may be able to mitigate those above issues by having a separate process/tool/cron-job that updates the labels separate from rendering, with compartmentalized access controls. 

## Capstone-Centric Rendering

In this approach, we ignore github milestones altogether. Instead, we use an explicit `dag capstone` label, then deduce the implied boxes for each capstone with some heuristic.

If capstone A and capstone B both depend on C, it's ambiguous which capstone box C should belong to. A basic requirement is that the assignment of C to A or B is deterministic from the DAG at the given runtime so that we don't "thrash" between alternatives with each rendering. If we pick some deterministic rule, it may mean we can't control C's assignment when we want to for project management reasons. If we introduce some other mechanism to do that, we're complicating the whole approach (and the appeal of this approach is to remove book-keeping by deriving the boxes automatically).

Some advantages:

- capstone goals are the immediate dependencies, and thus there's an explicit list that's managed the same way as all other dependencies.
- any transitive dependency of any capstone would automatically be included in _some_ capstone's box. By contrast, it's possible to add issues outside of a milestone and depend on them, in which case they are rendered outside of any box.

# Summary

Ok, I only brainstormed those two approaches. After writing them up, I'm leaning more towards `Automate Goal Issue Identification`

**Comment by str4d** [comment]
We've implemented a third option (#47): we still use GitHub milestones for issue grouping, and have introduced the `C-target` label for marking "target issues". The renderer can now produce a graph of just these target issues, and they can be organised independently of milestones.
